os: linux

language: java
services:
  - docker
cache: bundler
dist: bionic

install: skip

jobs:
  include:
    - name: failing
      script: true

    - name: windows deploy
      os: windows
      install: skip
      script: echo "Running on Windows"
      deploy:
        provider: # enter your provider details here
        dpl_version: 2.1.1

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
afte

