language: java

services:
  - docker

cache: bundler
dist: bionic

install: skip

jobs:
  include:
    - name: failing
      os: linux
      script: true

    - name: windows deploy
      os: windows
      install: skip
      script: echo "Running on Windows"
      deploy:
        provider: script
        script: echo "Deploying from Windows"
        on:
          branch: main

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT
