language: generic

jobs:
  include:
    - name: "Test DPLv2 on Windows"
      os: windows
      script:
        - bash ./build.sh
      deploy:
        provider: script
        script: echo "This would normally deploy using DPLv2"
        dpl_version: 2.0.0
