language: generic

jobs:
  include:
    - name: simple deploy job
      os: linux
      script: echo "Build complete"
      deploy:
        provider: script
        script: echo "Deploying..."
        dpl_version: 2.0.0
        on:
          branch: main
